### ISSUE TITLE
Error in orig[[nm]][i, , ..., drop = drop] : subscript out of bounds

### ISSUE THREAD

**Issue by Zifeng1995** [xuranw/MuSiC#61]
Hi, here. We used the ExpressionSet function to build the input datasets and run the MuSiC. However, there were something wrong.
The single-cell datasets and bulk datasets were as follows.
```
bulk.eset
ExpressionSet (storageMode: lockedEnvironment)
assayData: 38187 features, 844 samples 
  element names: exprs 
protocolData: none
phenoData
  sampleNames: MMRF_2272_1_BM_CD138pos MMRF_2762_1_BM_CD138pos ...
    MMRF_2419_2_BM_CD138pos (844 total)
  varLabels: case_id
  varMetadata: labelDescription
featureData: none
experimentData: use 'experimentData(object)'
Annotation:
```
```
SC.eset
ExpressionSet (storageMode: lockedEnvironment)
assayData: 33090 features, 1815 samples 
  element names: exprs 
protocolData: none
phenoData
  sampleNames: AGGTCCGAGATGCCAG-1_4 AGTGAGGTCTAGAGTC-1_8 ...
    GGCGACTCACGCCAGT-1_7 (1815 total)
  varLabels: orig.ident group ... sampleID (5 total)
  varMetadata: labelDescription
featureData: none
experimentData: use 'experimentData(object)'
Annotation:  
```

```
Est.prop.bulk = music_prop(bulk.eset = bulk.eset, sc.eset = SC.eset, clusters = 'seurat_clusters',
                               samples = 'sampleID', select.ct = c('0', '1', '2', '3','4', '5','6','7'),verbose = F)

```
`Error in orig[[nm]][i, , ..., drop = drop] : subscript out of bounds`

 Can anyone help me?

**Comment by paraish** [comment]
@Zifeng1995 Did you ever solve it? I'm getting the same error. 
Here is the Bulk ExpressionSet:
````
> bulk
ExpressionSet (storageMode: lockedEnvironment)
assayData: 20314 features, 81 samples 
  element names: exprs 
protocolData: none
phenoData: none
featureData: none
experimentData: use 'experimentData(object)'
Annotation:  
````
Here is the single cell ExpressionSet:
````
ExpressionSet (storageMode: lockedEnvironment)
assayData: 41336 features, 23875 samples 
  element names: exprs 
protocolData: none
phenoData
  sampleNames: AAACCTGAGTGTTAGA_1 AAACCTGCAAGCGCTC_1 ... TTTGTCATCTGTTTGT_6 (23875
    total)
  varLabels: X Barcode ... Sample_ID (6 total)
  varMetadata: labelDescription
featureData: none
experimentData: use 'experimentData(object)'
Annotation: 
````

And here is my call to Music, with the error returned:
```
>   music_results = music_prop(bulk.eset = bulk, 
+                              sc.eset = all_ref, 
+                              clusters = "Cluster",
+                              samples = "Sample",
+                              verbose = T)
Error in orig[[nm]][i, , ..., drop = drop] : subscript out of bounds
```
